### PR TITLE
Use standard OSG CI scripts

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
@ShawnMcKee, there appears to be a broken link that is causing the CI to fail:

```
ERROR   -  Error building page perfsonar/installation.md 
Error: The page "perfsonar/installation.md" contained a hyperlink to "perfsonar/perfsonar-in-osg.md" which is not listed in the "pages" configuration.
```

What should it be?

**Comment by marian-babik** [comment]
I have fixed the broken link, changed to ../perfsonar-in-osg.md

**Comment by ShawnMcKee** [comment]
Hi Brian,

Marian fixed it.  I assume the CI is again working?

Do you need to merge something now?

Thanks,

Shawn

**Comment by brianhlin** [comment]
I merged in Marian's changes and it looks like there's another error:

```
ERROR   -  Error building page perfsonar/faq.md 

Error: The page "perfsonar/faq.md" contained a hyperlink to "perfsonar/network-troubleshooting.md" which is not listed in the "pages" configuration.
```

@marian-babik: you can add commits to this PR (and thus kicking off the CI builds again) by pushing directly to my branch:

```
$ git remote add brianhlin https://github.com/brianhlin/security.git
$ git checkout -b <your branch name> brianhlin/master
<make your changes and commit them>
$ git push brianhlin <your branch>:master
```

**Comment by marian-babik** [comment]
Done that and fixed some other issues as well. Ended up with SSL errors when the build tries to check if https links are working, however some of those links do require a valid IGTF certificate, so I'm not sure how to fix this.

**Comment by brianhlin** [comment]
Unfortunately I haven't had luck getting SSL linkchecking working so I've just added them to the ignore list. I'll update it. How about this error, though?

```
URL        `http://www.es.net/introducing-esnet5/tools/'
Name       `http://www.es.net/introducing-esnet5/tools/'
Parent URL file:///home/travis/build/opensciencegrid/networking/site/network-troubleshooting/index.html, line 186, col 5
Real URL   http://www.es.net/about/tools
Check time 1.734 seconds
Info       Redirected to `http://www.es.net/about/tools'.
Result     Error: 404 Not Found
```

**Comment by marian-babik** [comment]
I missed that, but it's fixed now and build now fails with just SSL errors.

**Comment by brianhlin** [comment]
@marian-babik I'm a bad person and force pushed to my branch, overwriting your latest commit :(. Could you please fixup the esnet link again? Sorry about that.

**Comment by marian-babik** [comment]
No problem, re-done.

**Comment by brianhlin** [comment]
Thanks! It looks like deployment works so we should be done here.

**Pull request merged**
