### PR TITLE
Adding the 404 custom error

### PR DESCRIPTION
**Pull request by efajardo**
This PR is for ticket [3290](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3290). I added the same 404 pages from technology.

### CODE REVIEW

**Comment by efajardo** [comment]
@brianhlin can you review please?

**Comment by brianhlin** [comment]
@efajardo the CI submodule needs to be updated

**Comment by efajardo** [comment]
@brianhlin I updated the CI module but there are still broken links or "insecure" links. They should be fine except from `psds.opensciencegrid.org`

**Comment by brianhlin** [comment]
There are some links to various networking hosts where linkchecker doesn't like the SSL cert but this isn't related to Edgar's change. Merging

**Pull request merged**
